[tool.poetry]
name = "temporal"
version = "0.1.0"
description = "A Pytorch framework for building custom time-series models."
authors = ["Chris - chris@tensor-link.com"]
readme = "README.md"
packages = [{include = "temporal"}]

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.1"
transformers = "^4.48.2"
numpy = "^2.2.4"
scikit-learn = "^1.6.1"
joblib = "^1.4.2"
tqdm = "^4.67.1"
pyarrow = "^19.0.1"
datasets = "^2.21.0"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ruff = "^0.2.1"
pre-commit = "^3.6.2"
ipykernel = "^6.29.3"
build = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
