[project]
name = "temporal"
version = "0.1.0"
description = "A Pytorch framework for building custom time-series models."
authors = [
  { name = "Chris", email = "chris@tensor-link.com" }
]
readme = "README.md"
requires-python = ">=3.11"

# Main runtime dependencies
dependencies = [
  "torch>=2.3.1",
  "transformers>=4.48.2",
  "numpy>=2.2.4",
  "scikit-learn>=1.6.1",
  "joblib>=1.4.2",
  "tqdm>=4.67.1",
  "pyarrow>=19.0.1",
  "datasets>=2.21.0",
  "pandas>=2.2.3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.1.1",
  "ruff>=0.2.1",
  "pre-commit>=3.6.2",
  "ipykernel>=6.29.3",
  "build>=1.2.1",
]

[tool.setuptools.packages.find]
include = ["temporal"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
